image:
  name: gcr.io/kaniko-project/executor:v1.9.0-debug
  entrypoint: [""]


build-master:
  retry: 1
  stage: build
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE --registry-mirror eu0.regi.kube.gmp.io

    - DHAUTH=`"${CI_REGISTRY_USER_DH}:${$CI_REGISTRY_PASSWORD_DH}" | openssl base64 -A`
    - echo "{\"auths\":{\"$CI_REGISTRY_DH\":{\"auth\":\"DHAUTH\"}}}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE_DH:latest



  only:
    - master
